package com.romankryvolapov.localailauncher.domain.models

data class ModelMetadata(
    val magic: Int,
    val version: Int,
    val tensorCount: Long,
    val kvCount: Long,
    val generalArchitecture: String,
    val generalName: String,
    val generalFileType: String,
    val generalQuantizationVersion: Int,
    val llamaContextLength: Int,
    val llamaEmbeddingLength: Int,
    val llamaBlockCount: Int,
    val llamaFeedForwardLength: Int,
    val llamaRopeDimensionCount: Int,
    val llamaRopeFreqBase: Double,
    val llamaAttentionHeadCount: Int,
    val llamaAttentionHeadCountKv: Int,
    val llamaAttentionLayerNormRmsEpsilon: Double,
    val llamaExpertCount: Int,
    val llamaExpertUsedCount: Int,
    val tokenizerGgmlModel: String,
    val tokenizerGgmlTokens: List<String>,
    val tokenizerGgmlScores: List<Int>,
    val tokenizerGgmlTokenType: List<Int>,
    val tokenizerGgmlBosTokenId: Int,
    val tokenizerGgmlEosTokenId: Int,
    val tokenizerGgmlUnknownTokenId: Int,
    val tokenizerGgmlPaddingTokenId: Int,
    val tokenizerGgmlAddBosToken: Boolean,
    val tokenizerGgmlAddEosToken: Boolean,
    val tokenizerChatTemplate: String
)